### ISSUE TITLE
add docs for changing the output

### ISSUE THREAD

**Issue by drewwells** [superbrothers/zsh-kubectl-prompt#17]
Kops based clusters use FQDN. The names can be quite long, so it's helpful to mutate them. Add docs for how to modify variable correctly 

ie.

cluster.example.com ~> cluster

The below only works on initial load, then never changes
```
shortctx=$(echo -n $ZSH_KUBECTL_CONTEXT | sed 's/.example.com//')                                                    
RPROMPT='%{$fg[blue]%}($shortctx)%{$reset_color%}'
```

**Comment by drewwells** [comment]
This is how to do it with just zsh

```
setopt PROMPT_SUBST
RPROMPT='%{$fg[blue]%}$(kubectl config current-context | sed 's/.example.com//')%{$reset_color%}'

```

**Comment by superbrothers** [comment]
You can also use shell parameter expansion as follows:

```
setopt PROMPT_SUBST
RPROMPT='%{$fg[blue]%}(${ZSH_KUBECTL_PROMPT/.example.com/})%{$reset_color%}'
```

- https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html

**Comment by superbrothers** [comment]
This issue has no activities, so will be closed. If you have still a problem, please feel free to reopen it.
