### ISSUE TITLE
/Users/user/.kube/config doesn't exist

### ISSUE THREAD

**Issue by andreibogdan** [superbrothers/zsh-kubectl-prompt#18]
Hi,
On a OS X 10.15 i receive following error when loading plugin:
``` /Users/user/.kube/config doesn't exist ```
I checked the file and it does exists.

**Comment by andreibogdan** [comment]
the issue might be on stat command. https://ss64.com/osx/stat.html

**Comment by superbrothers** [comment]
I'm sorry for the late reply. Is this issue still unresolved?

**Comment by andreibogdan** [comment]
Yes, is unresolved. stat command that is used is not working on OS X. Also a nice improvement will be to allow to add custom kube config paths.

**Comment by superbrothers** [comment]
On my environment (macOS Catalina v10.15.1), I confirmed it works correctly. Could you tell me the detail of your environment, and the result of `ls -al $HOME/.kube`?

> Also a nice improvement will be to allow to add custom kube config paths.

That is already supported. If you set `KUBECONFIG` environment variable, it will use it as kubeconfig file.

**Comment by andreibogdan** [comment]
I tried with  export KUBECONFIG and the result is the same. `$HOME/.kube/sd/kubeconfig.yaml doesn't exist`.

**Comment by andreibogdan** [comment]
OS X version: 10.15.1

> ls -al $HOME/.kube                                                                                                     
> drwxr-x---    3 XXXX    96 Aug  7 17:41 cache
> lrwxr-xr-x    1 XXXX    40 Dec  9 14:40 config -> /Users/XXXX/.kube/sd/kubeconfig.yaml
> drwxr-x---  320 XXXX 10240 Dec  5 10:21 http-cache
> drwxr-xr-x    3 XXXX    96 Dec  5 10:21 sd

**Comment by elementalvoid** [comment]
In my case the problem occurs due to the order that zplug processes my config files. I have a "dot dir" full of local customizations. I defer the loading of this set of files so that all the zplug plugins load before my overrides. However, this means that the `path` variable changes after the kubectl-prompt plugin determines which `stat` command to use. So, by the time zsh attempts to render the plugin output the stat command has been swapped to the gnu version.

In my case the fix was simple: defer the kubectl-prompt plugin.
```sh
# Now all my local stuff . <-- this is my dot dir
zplug "~/.zshrc.d", from:local, use:"*.zsh", defer: 2

# kubectl -- deferred after the dot.d dir since it changes the $path var
# and that swaps the `stat` command used by the kube prompt
zplug superbrothers/zsh-kubectl-prompt, from:github, defer:3
export RPROMPT='%{$fg[$color]%}($ZSH_KUBECTL_PROMPT)%{$reset_color%}'
```

**Comment by superbrothers** [comment]
@andreibogdan Could you show me the result of the following commands:
```bash
kubectl version --client
kubectl config view >/dev/null && echo $?
KUBECONFIG=$HOME/.kube/sd/kubeconfig.yaml kubectl config view >/dev/null && echo $?

if stat --help >/dev/null 2>&1; then
  modified_time_fmt='-c%y' # GNU coreutils
else
  modified_time_fmt='-f%m' # FreeBSD
fi
echo $modified_time_fmt
stat -L $modified_time_fmt $HOME/.kube/config
```

(I'll add a feature which allows us to easily debug.)

**Comment by andreibogdan** [comment]
`$ kubectl version --client`
`Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:29Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}`
`$ kubectl config view >/dev/null && echo $?`
`0`

`if stat --help >/dev/null 2>&1; then
  modified_time_fmt='-c%y' # GNU coreutils
else
  modified_time_fmt='-f%m' # FreeBSD
fi
echo $modified_time_fmt`
`-f%m`
`stat -L $modified_time_fmt $HOME/.kube/config`
`stat: bad file descriptor`

**Comment by philmtd** [comment]
I also ran into this issue. I'm using oh-my-zsh and in my `.zshrc` file I added several gnu tools to my `PATH`. I did that modification after loading zsh. 

I solved this problem by modifying my `PATH` before declaring the oh-my-zsh `plugins=(...)`.

**Comment by alextes** [comment]
For me this seems to have something to do with how zgen only executes the `if ! zgen saved; then` block, which contains `zgen load superbrothers/zsh-kubectl-prompt`, if it hasn't saved its init file. Meaning it works once after `zgen reset` is ran, which removes the `init.zsh` file, and fails on every consequent loading of the shell. I have to source `kubectl.zsh` outside of zgen's conditional block to make this error disappear.

**Comment by superbrothers** [comment]
I have created a PR #20 to fix this issue. Can someone please confirm that it solves the problem?

**Comment by alextes** [comment]
@superbrothers fixes it for me 👍

**Comment by superbrothers** [comment]
@alextes Thanks for checking! 🥳
