### ISSUE TITLE
Only show context/namespace inside k8s projects

### ISSUE THREAD

**Issue by alextes** [superbrothers/zsh-kubectl-prompt#19]
Can we think of some way to only show this great right-side prompt when you're working in a directory that deals with kubernetes? I definitely don't need to see it all the time. Only when I'm working on any of my kubernetes projects, as usually indicated by my current working directory.

Ideas for how to implement:
1. list of directories that when matching make the prompt appear.
2. some file in current directory signaling this is a kubernetes project. Sadly, kubernetes doesn't have this already.
3. start showing it after kubectl is invoked for the first time

**Comment by superbrothers** [comment]
Just a thought, but how about preparing dedicated prompt settings for Kubernetes work and loading it as needed? Whatever triggers, the bottom line is that it will load dedicated settings.

**Comment by alextes** [comment]
That could work. I haven't seen a plugin like that but I'm sure there is one or it wouldn't be all that hard to write one. On the other hand, the trend I've seen is that the prompt detects and appears when e.g. you enter a node project directory or you load a python virtualenv.

I think I'll adjust my zshrc so that when I run `kubectl` it starts showing this prompt.
