### ISSUE TITLE
kubectl_prompt not changed on windows terminal

### ISSUE THREAD

**Issue by gamggi** [superbrothers/zsh-kubectl-prompt#21]
3days ago, I used windows terminal installed ubuntu 18.04 wsl2

zsh-kubectl-prompt has some problem when kubectl context changed, that not changed kubectl_prompt 

![kubectl_prompt](https://user-images.githubusercontent.com/231440/89164644-4fec4280-d5b2-11ea-8e1a-45f5359ab9d3.png)

**Comment by superbrothers** [comment]
Could you tell me more details of your environment?

- zsh-kubectl-prompt git-hash (e.g: `cd repo; git rev-parse HEAD`): 
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Zsh version (e.g: `zsh --version`)
- Others:

**Comment by gamggi** [comment]
zsh-kubectl-prompt git-hash (e.g: cd repo; git rev-parse HEAD):
   f6bc949c05fd18ee557a89c92f82ff556200707d

Kubernetes version (use kubectl version):
   Client Version: v1.17.3
   Server Version: v1.17.9

OS (e.g: cat /etc/os-release):
  NAME="Ubuntu"
  VERSION="18.04.2 LTS (Bionic Beaver)"

Zsh version (e.g: zsh --version)
  zsh 5.4.2 (x86_64-ubuntu-linux-gnu)

Others:
  Windows terminal version
    - 1.1.2021.0
  wsl version:
    - Ubuntu-18.04    version 1


sorry, i knew to use wsl2, but i use wsl1 ubuntu 18.04.

**Comment by superbrothers** [comment]
I don't have a Windows environment, so I'll check if it can be reproduced on a VM running Ubuntu 18.04.

**Comment by gamggi** [comment]
I found what the problem is. It was my mistake.
I used double quotes instead of single quotes. :( 

RPROMPT=**"**%{$fg[blue]%}($ZSH_KUBECTL_PROMPT)%{$reset_color%}**"**

After quotes change, it works fine.

![제목 없음](https://user-images.githubusercontent.com/231440/89252090-bbd2b780-d653-11ea-9d97-2b6aba81d5fb.png)


thank you
