### ISSUE TITLE
custom color depending on context does not update within current shell

### ISSUE THREAD

**Issue by ranvit** [superbrothers/zsh-kubectl-prompt#23]
I have the following in my .zshrc
```
autoload -U colors; colors
source $(brew ls zsh-kubectl-prompt | grep 'kubectl.zsh')
[[ "$(kubectl config current-context)" =~ "PRODUCTION" ]] && color=red || color=green
RPROMPT='%{$fg[$color]%}[$ZSH_KUBECTL_PROMPT]%{$reset_color%}'
# customization
zstyle ':zsh-kubectl-prompt:' separator '|' 
```
I want the color of the prompt to be red if my context is the production cluster.

For starters, I was unable to use `ZSH_KUBECTL_CONTEXT` (it doesn't get set in my environment), so I'm calling `kubectl config current-context` again

**My problem**:

Suppose I'm on my `development` context, the prompt color is green. Then I switch my context to `production` - I expect to see the prompt color change to red. It remains green instead of changing to red.
However, opening a new shell forces the prompt color to change to red.

I'm probably not doing something correct, please help.

**Comment by ranvit** [comment]
I figured out that this line is not updating the `$color` variable when we are switching kubernetes contexts.

```
[[ "$(kubectl config current-context)" =~ "PRODUCTION" ]] && color=red || color=green
```

Manually setting the `$color` variable immediately updates the prompt color
```
color=blue
```

**Comment by ranvit** [comment]
## GOT IT
Someone feel free to correct my work.

So, this is the important line where color is being set into the right-prompt. Whatever `RPROMT` contains is what gets re-executed on every terminal entry/command.
```
RPROMPT='%{$fg[$color]%}[$ZSH_KUBECTL_PROMPT]%{$reset_color%}'
```

And from my previous comment we know that the `$color variable is not getting re-calculated. Thats because this line is not getting re-run on every terminal command
```
[[ "$(kubectl config current-context)" =~ "PRODUCTION" ]] && color=red || color=green
```
---
### The solution
is to put that color calculation logic into the RPROMPT. This works for me now! Like so
```
RPROMPT='%{$fg[$([[ "$(kubectl config current-context)" =~ "aks-prod" ]] && echo red || echo green)]%}[$ZSH_KUBECTL_PROMPT]%{$reset_color%}'
```
---
On a different note, I found it nicer to set the background color to red/green as opposed to the foreground. This is what I'm using
```
RPROMPT='%{$bg[$([[ "$(kubectl config current-context)" =~ "PRODUCTION" ]] && echo red || echo green)]$fg[black]%}[$ZSH_KUBECTL_PROMPT]%{$reset_color%}'
```

**Comment by superbrothers** [comment]
I'm sorry for the late reply.

> ### The solution
> is to put that color calculation logic into the RPROMPT. This works for me now! Like so
> ```
> RPROMPT='%{$fg[$([[ "$(kubectl config current-context)" =~ "aks-prod" ]] && echo red || echo green)]%}[$ZSH_KUBECTL_PROMPT]%{$reset_color%}'
> ```

zsh-kubectl-prompt creates the followting 4 variables:

- `ZSH_KUBECTL_CONTEXT`
- `ZSH_KUBECTL_NAMESPACE`
- `ZSH_KUBECTL_PROMPT`
- `ZSH_KUBECTL_USER`

So, using `ZSH_KUBECTL_CONTEXT`, you can do the following:

```
RPROMPT='%{$fg[$([[ "$ZSH_KUBECTL_PROMPT" =~ "aks-prod" ]] && echo red || echo green)]%}[$ZSH_KUBECTL_PROMPT]%{$reset_color%}'
```

This is light way because it does not run `kubectl config current-context` command.

If you have more complicated conditions, I recommend to define it as a function.

```bash
function right_prompt() {
  local color="green"

  if [[ "$ZSH_KUBECTL_CONTEXT" =~ "aks-prod" ]]; then
    color="red"
  fi

  echo "%{$fg[$color]%}[$ZSH_KUBECTL_PROMPT]%{$reset_color%}"
}

RPROMPT='$(right_prompt)'
```
