### ISSUE TITLE
context is not shown

### ISSUE THREAD

**Issue by sorushsaghari** [superbrothers/zsh-kubectl-prompt#25]
I am using oh-my-zsh and , I have done the 2 steps mentioned for oh-my-zsh, even the environment variables are set but I can't see the prompt 
![image](https://user-images.githubusercontent.com/38028950/98438330-b6778400-20fe-11eb-8dfc-d22f9b5618cc.png)

**Comment by beyondbill** [comment]
Same here

**Comment by pbarker** [comment]
also same 😢

**Comment by superbrothers** [comment]
@beyondbill @pbarker Thanks for your reports. I've added README.md.

You need to configure your prompt as follows (or check how to customize the theme plugin you are using)

```sh
RPROMPT='%{$fg[blue]%}($ZSH_KUBECTL_PROMPT)%{$reset_color%}'
```
